version: "3.7"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start --import-realm
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - 8081:8080
    restart: always
    healthcheck:
      test: (timeout 10s bash -c ":> /dev/tcp/keycloak/8081" && timeout 10s bash -c ":> /dev/tcp/keycloak/8443") || exit 1
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - ./imports/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json


  web-app:
    build: .

  oauth2-proxy:
    image: bitnami/oauth2-proxy:7.6.0
    depends_on:
      redis:
        condition: service_started
      keycloak:
        condition: service_healthy
    command:
      - --http-address
      - 0.0.0.0:4180
    environment:
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: Keycloak
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true
      OAUTH2_PROXY_REDIRECT_URL: http://localhost/oauth2/callback

      OAUTH2_PROXY_OIDC_ISSUER_URL: http://localhost:8081/realms/myrealm
      OAUTH2_PROXY_CLIENT_ID: myclient
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}

      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: true
      OAUTH2_PROXY_OIDC_EXTRA_AUDIENCES: k8s
      OAUTH2_PROXY_OIDC_EMAIL_CLAIM: sub
      OAUTH2_PROXY_EXTRA_JWT_ISSUERS: http://localhost:8082/realms/myrealm2=k8s


      OAUTH2_PROXY_SET_XAUTHREQUEST: true
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true

      OAUTH2_PROXY_SESSION_STORE_TYPE: redis
      OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://redis

      OAUTH2_PROXY_COOKIE_REFRESH: 30m
      OAUTH2_PROXY_COOKIE_NAME: SESSION
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
    ports:
      - 4180:4180

  nginx:
    image: nginx:1.21.6-alpine
    depends_on:
      - keycloak
      - oauth2-proxy
      - web-app
    volumes:
      - ./nginx-default.conf.template:/etc/nginx/templates/default.conf.template
      - ./static-html:/usr/share/nginx/html # Not covered in blog post, adds a simple HTML page to test sign-out
    ports:
      - 80:80

  redis:
    image: redis:7.0.2-alpine3.16
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
